### ISSUE TITLE
Second post about color codes still appear when the permissions are false

### ISSUE THREAD

**Issue by KahpotVanilla** [wikmor/LPC#9]
Yet still it appears, the permission is false and people still can type with colors

**Comment by wikmor** [comment]
Hey, I've checked the issue again. On my side seems working just fine. Make sure you don't have operator status. Also, you don't have to negate the permission, since it's for OP by default. Please check once again, if you have downloaded the latest version - 3.4.1 and if any other chat plugin doesn't change it.

**Comment by KahpotVanilla** [comment]
I'll check once again, thanks!
